App\Entity\Categoria:
    attributes:
        id:
            groups: ['categoria', 'restaurante_list', 'categoria_restaurante']
        categoria:
            groups: ['categoria','categoria_list', 'restaurante_list']