App\Entity\Cliente:
  properties:
    nombre:
      - NotBlank:
          message: 'Debe indicar un nombre'
    apellidos:
      - NotBlank:
          message: 'Debe indicar sus apellidos'
    telefono:
      - NotBlank:
          message: 'Debe indicar un númnero de teléfono'